# This workflow uses ServiceNow custom actions that are certified by ServiceNow.

name: ARTIFACT2 CI GitHub workflow

on: 
  push:
   branches: [  "feature-*" ]
  workflow_dispatch:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
       echo "artifact=$(echo ${cat release.txt | grep -i comp | cut -d ":" -f2})" >> "$GITHUB_ENV"
       echo artifact name is $env.artifact
      #run: mvn clean compile --file artifact2/pom.xml 

  test:
    name: 'Test'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.0.0
    - name: Run Tests with Maven
      run: mvn -B test --file artifact2/pom.xml 
  publish-job:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: mvn --batch-mode --update-snapshots verify --file artifact2/pom.xml 
    - run: mvn test --file artifact2/pom.xml 
    - run: mkdir staging && cp artifact2/target/*.jar staging && cp artifact2/target/surefire-reports/*.xml staging
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging
  deploytodev:
    name: 'Deploytodev'
    needs: publish-job
    runs-on: ubuntu-latest
    steps:
    - name: Run deployment scripts
      run: echo 'Deployment step in progress...'
